LGCNS-PJT-EDU/EDU_AI

.github/workflows/deploy.yml, Dockerfile
=> fix: yml 수정

k8s/deployment.yaml
=> feat: deployment.yml 추가

.github/workflows/deploy.yml
=> fix: 이미지 태그 수정

k8s/service.yml
=> feat: service.yml 추가

k8s/service.yml
=> fix: service.yml 수정

.github/workflows/integration.yml
=> fix: CI 파일명 수정

.github/workflows/integration.yml, k8s/deployment.yaml
=> fix: Argo yml 파일 수정

app/models/pre_assessment/request.py, app/models/pre_assessment/response.py, app/routers/post_assessment_router.py, app/routers/pre_assessment_router.py, app/services/assessment/common.py
- 사전 평가 결과 저장 기능 구현
- 사전 평가 결과 저장 기능 구현
- 기능 연동
- Spring Boot 측 수정 내용은 https://lgcnsampjt.slack.com/archives/C08MFPV3TGX/p1747446920075819 참고
=> EDU-332 사전 평가 결과 저장 기능

app/routers/post_assessment_router.py, app/services/assessment/post.py
- 사후 평가 저장 기능 구현
- 사후 평가 저장 기능
- 여러 회차의 평가를 저장할 수 있도록 구현
=> EDU-346 feat: 사후 평가 결과 저장 기능 추가

app/routers/post_assessment_router.py, app/routers/pre_assessment_router.py
- 사후 평가 문제 반환 기능 구현
- 사후 평가 문제 반환 기능 구현
- 불필요한 주석 제거
- API 초안 코드 제거
=> Edu 345 사후 평가 문제 반환 기능 구현

k8s/deployment.yaml
- argo deployment.yaml
- argo가 새 이미지를 감지 못 하는 에러 수정 중
-
=> fix: argo deployment.yaml

app/routers/recommend.py, app/routers/reviewnote_router.py
=> EDU-348 refactor: 추천컨텐츠 및 오답노트

app/clients/__init__.py, app/clients/mongodb.py, app/clients/openai_client.py, app/routers/feedback_router.py, app/routers/post_assessment_router.py, app/routers/pre_assessment_router.py, app/services/assessment/common.py, app/services/assessment/post.py, app/services/common/common.py, app/services/feedback/builder.py, app/services/prompt/builder.py, app/utils/build_feedback_prompt.py
- 피드백 생성 기능 구현
- OpenAI 연결 오류 해결
- 피드백 생성 기능 구현
=> EDU-371 피드백 생성 기능 구현

app/consumer/feedback_consumer.py, app/main.py, app/producer/feedback_producer.py, app/routers/feedback_router.py, app/routers/pre_assessment_router.py, poetry.lock, pyproject.toml
=> feat: kafka-python -> aiokafka

Dockerfile, requirements.txt
- dockerFile 수정
- dockerFile 수정
-
=> fix: dockerFile

Dockerfile, app/routers/feedback_router.py, app/services/prompt/builder.py, app/utils/build_feedback_prompt.py
- dockerFile, 프롬프트 수정
- dockerFile, 프롬프트 수정
-
=> fix: dockerFile , 프롬프트

app/consumer/feedback_consumer.py, app/models/feedback/request.py, app/routers/feedback_router.py, app/services/common/common.py, app/services/prompt/builder.py, app/utils/build_feedback_prompt.py
- feedback 생성 기능에 Kafka를 연동
- 피드백 생성 기능에 Kafka를 연동
- 차후에 feedback router 삭제 예정
=> EDU-444 피드백 생성 기능에 kafka를 연결

app/routers/feedback_router.py
- feedback 조회 시 userId와 subjectId 모두를 사용하도록 수정
- 로컬에서 테스트 완료
=> EDU-462 refactor: feedback 조회 시 subjectId도 사용하도록 수정

Dockerfile
=> fix: Python 베이스 이미지 버전 수정

app/consumer/feedback_consumer.py, app/consumer/recommendation_consumer.py, app/main.py
=> fix: 카프카 heartbeat 등 수정
